mutation changePass(
	$email: String!
	$password: String!
	$newPassword: String!
) {
	updateUser(
		arg1: { email: $email, newPassword: $newPassword, password: $password }
	) {
		token
		role
		id
	}
}
