query getBookmarks($filter: bookmarks_bool_exp) {
	bookmarks(where: $filter) {
		id
		recipe {
			title
			duration
			coverImage
			created_at
			reviews_aggregate {
				aggregate {
					avg {
						rating
					}
				}
			}
			likes_aggregate {
				aggregate {
					count
				}
			}
		}
		recipe_id
	}
}
